name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v4

      - name: Get tools
        run: |
          sudo apt-get update
          sudo apt-get install p7zip-full -y
          curl -L https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18.4/makerom-v0.18.4-ubuntu_x86_64.zip
          sudo 7z e makerom-v0.18.4-ubuntu_x86_64.zip
          sudo chmod +x makerom
          mv makerom /usr/local/bin
          rm makerom-v0.18.4-ubuntu_x86_64.zip

      - name: Build Project
        run: |
          make
          make cia

      - uses: actions/upload-artifact@v4
        with:
          name: SpotPassDumper11
          path: |
           SpotPassDumper11.3dsx
           SpotPassDumper11.cia
          if-no-files-found: error
