name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v4

      - name: Build Project
        run: make

      - uses: actions/upload-artifact@v4
        with:
          name: SpotPassDumper11.zip
          path: |
           SpotPassDumper11.3dsx
           SpotPassDumper11.smdh
          if-no-files-found: error
