name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v1

#      - name: Fix apt sources
#        run: |
#          apt-get update
#          apt-get -y install dirmngr
#          echo 'deb http://us.archive.ubuntu.com/ubuntu/ bionic main' >> /etc/apt/sources.list
#          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
#          apt-get update

      - name: Build Project
        run: make

      - uses: actions/upload-artifact@v2
        with:
          name: SpotPassDumper11.3dsx
          path: .
          if-no-files-found: error
          name: SpotPassDumper11.smdh
          path: .
          if-no-files-found: error
